version: '3.8'
services:
  gradio-app:
    build:
      context: .
      dockerfile: gradio/Dockerfile
    ports:
      - "7860:7860"
    depends_on:
      - model_api

  model_api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "5005:5005"
